import assert from "node:assert/strict";
import fs from "node:fs";

const read = (name) => fs.readFileSync(name, "utf8");
const page = read("app/(app)/blueprints/[stackId]/page.tsx");
const client = read("app/(app)/blueprints/[stackId]/BlueprintWorkspaceClient.tsx");
const card = read("src/components/BlueprintWellnessOverviewCard.tsx");
const generator = read("src/lib/generateStack.ts");
const decisions = read("src/lib/recommendationDecisionData.ts");
const proposals = read("src/lib/reportRecommendationProposals.ts");
const overview = read("src/lib/blueprintWellnessOverview.ts");
const release = read("scripts/release-gate.mjs");
const connectedLoader = read("src/lib/connectedHealthData.ts");
const handoffLoader = read("src/lib/healthContextHandoffData.ts");
const regimen = read("src/lib/currentRegimen.ts");
const routineClient = read("app/(app)/routine/RoutineClient.tsx");

assert.match(page, /\.eq\("user_id", user\.id\)/);
assert.match(page, /getMemberIntelligenceContext\(user\.id\)/);
assert.match(page, /blueprintSafetyCandidates\(storedMarkdown, \[/, "Live safety must include saved report proposals, not only the current routine.");
assert.match(page, /loadConnectedHealthSummary\(admin, user\.id\)/);
assert.match(page, /loadLatestHealthContextHandoff\(admin, user\.id\)/);
assert.match(connectedLoader, /\.eq\("user_id", userId\)/);
assert.match(handoffLoader, /\.eq\("user_id", userId\)/);
assert.match(page, /blueprintOverviewLocalDate/);
assert.match(page, /originalBody: displayed !== body \? body : null/);
assert.doesNotMatch(page, /\.update\(|\.delete\(|\.insert\(/, "Displaying the overview must not rewrite saved records.");
assert.match(overview, /handoff\?\.memberApproved === true/);
assert.match(overview, /checkIn\?\.date === asOfDate/);
assert.match(overview, /latest\?\.local_date === asOfDate/);
assert.doesNotMatch(overview, /fetch\(|OpenAI|supabase|raw_payload|lab_history/);
assert.match(card, /separate from the original dated report and PDF/);
assert.match(card, /Historical records are not live sync/);
assert.match(card, /aria-labelledby="blueprint-wellness-title"/);
assert.match(client, /<BlueprintWellnessOverviewCard overview=\{wellnessOverview\}/);
assert(client.indexOf("<BlueprintWellnessOverviewCard") < client.indexOf("<RecommendationDecisionPanel"));
assert.match(client, /Read the original saved recommendations/);
assert.match(client, /The saved report and PDF are unchanged/);
assert.match(client, /item\.decision\.overlap_snapshot\.length\) \{[\s\S]*?Nothing was added[\s\S]*?return;/);
assert.match(client, /recommendationNeedsClinicianReview\(item\.proposal\.notes\)/);
assert.match(client, /clinicianReview \? "Add after review" : "Add to Routine"/);
assert.match(client, /item\.decision\.overlap_snapshot\.length \? \([\s\S]*?Review overlap in Routine[\s\S]*?\) : \([\s\S]*?Add to Routine/);
assert.match(decisions, /currentItems\.filter\(\(item\) => item\.active !== false\)/);
assert.match(decisions, /seenProposalNames/);
assert.match(decisions, /reportNotes\.get\(healthItemIdentityKey\(item\.name\)\)/, "Live report restrictions must reach the decision controls without dropping saved notes.");
assert.doesNotMatch(decisions, /\.delete\(/, "Filtering duplicate ideas must preserve stored history.");
const adoption = regimen.slice(regimen.indexOf("export async function adoptStackRecommendation"), regimen.indexOf("export async function upsertManualRegimenItem"));
assert.match(adoption, /classifyBlueprintRecommendation\(item\.name, await getCurrentRegimen\(userId\)\)/);
assert.match(adoption, /recommendation_already_recorded/);
assert.match(adoption, /recommendation_overlap_review_required/);
assert(adoption.indexOf("recommendation_overlap_review_required") < adoption.indexOf(".upsert(row"), "Reject duplicates and overlaps before any routine overwrite.");
assert.match(routineClient, /recommendation_overlaps\?\.length \? \([\s\S]*?Review recorded supplements[\s\S]*?: <button/);
assert.match(routineClient, /recommendation_overlap_review_required/);
assert.match(proposals, /classifyBlueprintRecommendation\(name, currentItems\)\.status === "New - consider"/);
const intro = generator.slice(generator.indexOf("function buildPersonalizedIntroSection"), generator.indexOf("function buildNeutralGoalsSection"));
assert.match(intro, /blueprintWellnessIntroMarkdown\(buildBlueprintWellnessOverview/);
assert.doesNotMatch(intro, /first additions|newBlueprint/);
const dosing = generator.slice(generator.indexOf("function consistentDosingBody"), generator.indexOf("function assembleCanonicalReport"));
assert(dosing.indexOf('classification.status === "Clinician review"') < dosing.indexOf("formatStartingGuidance(name)"));
assert.match(dosing, /no starting dose or new schedule is supplied/);
assert.match(dosing, /healthItemIdentityKey\(item\.name\) === healthItemIdentityKey\(name\)/, "Never copy a blend's dose onto an overlapping standalone ingredient.");
assert.doesNotMatch(generator, /Math\.max\(4, minRows/);
assert.match(read("src/lib/blueprintWorkspace.ts"), /BLUEPRINT_ENGINE_VERSION = "2026-10-04\.1"/);
assert.match(release, /qa:blueprint-overview/, "Keep this regression check in the permanent release gate.");

console.log("Blueprint overview ownership, preservation and interface assertions passed.");
