import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(path, "utf8");
const loader = read("src/lib/importedHealthContextData.ts");
assert(loader.includes('import "server-only"'));
assert(loader.includes('.eq("user_id", userId)'));
assert(loader.includes('.eq("raw_payload->>schema_version", "member_source_archive_v1")'));
assert(!loader.includes("user_email"));
const today = read("app/(app)/today/page.tsx");
assert(today.includes("supabase.auth.getUser()"));
assert(today.includes("loadImportedHealthSummary(supabase, user.id)"));
const member = read("src/lib/memberContextData.ts");
assert(member.includes("loadImportedHealthSummary(admin, userId)"));
const generator = read("src/lib/generateStack.ts");
assert(generator.includes("const recommendableSupplementLedger = buildEvidenceEligibleSupplementCandidates("));
assert(generator.includes("Missing aligned evidence for Blueprint recommendations:"), "Final evidence validation must remain fail-closed");
assert(generator.includes("for (const item of currentStackLedger)"), "Unsupported reported items must remain in the persisted source ledger");
assert(generator.includes("...withoutSubmissionSourcePayloads(sub)"));
assert(generator.includes("imported_health_records: sub?.imported_health_records ?? null"));
assert(generator.slice(generator.indexOf("function summarizeForLLM"), generator.indexOf("function normalizeBrandPref")).includes("imported_health_records:"));
assert(generator.slice(generator.indexOf("function compactForPassC"), generator.indexOf("function compactForPassC") + 1600).includes("imported_health_records:"));
assert.equal((generator.match(/\$\{IMPORTED_HEALTH_PROMPT_RULES\}/g) ?? []).length, 4);
const coach = read("src/lib/ai/contextualCoachData.ts");
assert(coach.includes("facts.imported_health_records = importedRecords"));
assert(coach.includes("IMPORTED_HEALTH_PROMPT_RULES,"));
assert(coach.includes('routing.intent === "GENERAL_EDUCATION" && isImportedHealthRecordLookup(question)'));
assert(coach.includes('["imported_health_records", "recent_check_ins", "context_status"]'), "Record lookups must not retrieve supplement recommendation candidates");
assert(coach.indexOf('["imported_health_records", "recent_check_ins", "context_status"]') < coach.indexOf('activeExclusions.forEach'), "Optional check-in exclusions must also apply to record lookups");
const routing = read("src/lib/contextualCoach.ts");
assert(routing.indexOf('if (isImportedHealthRecordLookup(question))') > routing.indexOf('return route("SAFETY_REVIEW")'), "Safety routing must precede read-only archive lookup");
assert(read("src/lib/coachTaskValidation.ts").includes("dated_imported_records_and_source_caveats_required"));
const activation = read("src/lib/premiumActivation.ts");
assert(activation.includes('admin.from("submissions").select("id").eq("user_id", user.id)'));
assert(activation.includes('status: "missing", stackId: null, createdAt: null, intakeSubmissionId'));
const checklist = read("src/components/activation/PremiumActivationChecklist.tsx");
assert(checklist.includes("/results/premium?submission_id="));
assert(checklist.includes("&from_saved_profile=1"));
assert(checklist.includes("Create Blueprint from my saved profile"));
const handoff = read("app/(app)/results/premium/page.tsx");
assert(handoff.includes('searchParams.get("from_saved_profile") === "1"'));
assert(handoff.includes('name: "ready_to_generate"'));
assert(handoff.includes("fromSavedProfile && !generationStartedRef.current"));
assert(handoff.includes("generationStartedRef.current = true"));
assert(handoff.includes("Create my Blueprint"));
assert(handoff.includes('fetch("/api/generate-stack", {'));
assert(handoff.indexOf('json.status === "ready"') < handoff.indexOf('if (fromSavedProfile'), "An existing Blueprint must win over the saved-profile prompt");
const card = read("src/components/dashboard/ConnectedHealthCard.tsx");
assert(card.includes("not live sync"));
assert(card.includes("Reference interval"));
assert(card.includes("Your imported source archive stays private"));
assert(!read("app/(app)/today/TodayClient.tsx").includes("raw_payload"));
console.log("Imported health architecture: owner-bound server reads, bounded prompts and saved-intake activation assertions passed.");
