create table if not exists public.weekly_experiments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on update cascade on delete cascade,
  source_stack_id uuid references public.stacks(id) on delete set null,
  source_action_id text,
  identity_direction text,
  action_label text,
  cue text,
  frequency_per_week smallint,
  minimum_version text,
  reminder_preference text not null default 'none',
  onboarding_step smallint not null default 0,
  status text not null default 'draft',
  week_start date not null default (date_trunc('week', current_date)::date),
  activated_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weekly_experiments_source_action_length check (source_action_id is null or char_length(source_action_id) <= 80),
  constraint weekly_experiments_identity_direction check (
    identity_direction is null or identity_direction in (
      'movement', 'nutrition', 'sleep', 'emotional_health',
      'relationships', 'focus', 'career', 'happiness', 'overall_health'
    )
  ),
  constraint weekly_experiments_action_length check (action_label is null or char_length(action_label) between 4 and 240),
  constraint weekly_experiments_cue_length check (cue is null or char_length(cue) between 2 and 160),
  constraint weekly_experiments_frequency check (frequency_per_week is null or frequency_per_week between 1 and 7),
  constraint weekly_experiments_minimum_length check (minimum_version is null or char_length(minimum_version) between 2 and 160),
  constraint weekly_experiments_reminder check (reminder_preference in ('none', 'email')),
  constraint weekly_experiments_onboarding_step check (onboarding_step between 0 and 6),
  constraint weekly_experiments_status check (status in ('draft', 'active', 'completed', 'archived'))
);

create unique index if not exists weekly_experiments_one_current_per_user
  on public.weekly_experiments (user_id)
  where status in ('draft', 'active');

create index if not exists weekly_experiments_user_updated_idx
  on public.weekly_experiments (user_id, updated_at desc);

alter table public.weekly_experiments enable row level security;

create policy "weekly_experiments: select own"
  on public.weekly_experiments for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "weekly_experiments: insert own"
  on public.weekly_experiments for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "weekly_experiments: update own"
  on public.weekly_experiments for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "weekly_experiments: delete own"
  on public.weekly_experiments for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.weekly_experiments to authenticated;

create table if not exists public.activation_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on update cascade on delete cascade,
  experiment_id uuid references public.weekly_experiments(id) on delete set null,
  event_name text not null,
  step smallint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint activation_events_name check (
    event_name in ('activation_started', 'step_completed', 'activation_completed', 'activation_resumed')
  ),
  constraint activation_events_step check (step is null or step between 0 and 6),
  constraint activation_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists activation_events_user_created_idx
  on public.activation_events (user_id, created_at desc);

create index if not exists activation_events_experiment_idx
  on public.activation_events (experiment_id, created_at);

alter table public.activation_events enable row level security;

create policy "activation_events: select own"
  on public.activation_events for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "activation_events: insert own"
  on public.activation_events for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

grant select, insert on public.activation_events to authenticated;
grant usage, select on sequence public.activation_events_id_seq to authenticated;

comment on table public.weekly_experiments is
  'One small weekly lifestyle practice configured during paid activation. Supplement and medication actions are excluded in application validation.';

comment on table public.activation_events is
  'Privacy-safe paid activation funnel events. Metadata must not contain health or action text.';
