create schema if not exists analytics;

revoke all on schema analytics from public, anon, authenticated;
grant usage on schema analytics to service_role;

create table public.product_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid,
  user_id uuid references public.users(id) on update cascade on delete set null,
  experiment_id uuid references public.weekly_experiments(id) on update cascade on delete set null,
  event_name text not null,
  source text not null,
  plan text,
  step smallint,
  event_key text unique,
  created_at timestamptz not null default now(),
  constraint product_events_identity check (visitor_id is not null or user_id is not null),
  constraint product_events_name check (event_name in (
    'homepage_viewed', 'pricing_viewed', 'intake_started', 'intake_completed',
    'blueprint_viewed', 'blueprint_action_selected', 'checkout_started',
    'checkout_completed', 'activation_started', 'activation_completed',
    'practice_completed', 'check_in_completed', 'weekly_review_opened',
    'weekly_review_completed', 'subscription_cancelled'
  )),
  constraint product_events_source check (source in (
    'homepage', 'pricing', 'tally', 'results', 'upgrade', 'stripe',
    'onboarding', 'today', 'daily_log', 'weekly_review'
  )),
  constraint product_events_plan check (plan is null or plan in ('monthly', 'annual')),
  constraint product_events_step check (step is null or step between 0 and 6),
  constraint product_events_event_key_length check (event_key is null or char_length(event_key) between 8 and 180)
);

create index product_events_user_created_idx
  on public.product_events (user_id, created_at desc)
  where user_id is not null;

create index product_events_visitor_created_idx
  on public.product_events (visitor_id, created_at desc)
  where visitor_id is not null;

create index product_events_name_created_idx
  on public.product_events (event_name, created_at desc);

create index product_events_experiment_idx
  on public.product_events (experiment_id, created_at)
  where experiment_id is not null;

alter table public.product_events enable row level security;

revoke all on table public.product_events from public, anon, authenticated;
revoke all on sequence public.product_events_id_seq from public, anon, authenticated;
grant select, insert on table public.product_events to service_role;
grant usage, select on sequence public.product_events_id_seq to service_role;

insert into public.product_events (
  user_id, experiment_id, event_name, source, step, event_key, created_at
)
select
  ranked.user_id,
  ranked.id,
  'activation_completed',
  'onboarding',
  6,
  'activation:completed:' || ranked.id::text,
  ranked.activated_at
from (
  select
    experiments.*,
    row_number() over (partition by user_id order by activated_at, created_at) as activation_number
  from public.weekly_experiments experiments
  where activated_at is not null
) ranked
where ranked.activation_number = 1
on conflict (event_key) do nothing;

insert into public.product_events (
  user_id, experiment_id, event_name, source, event_key, created_at
)
select
  completions.user_id,
  completions.experiment_id,
  'practice_completed',
  'today',
  'practice:' || completions.experiment_id::text || ':' || completions.completion_date::text,
  completions.created_at
from public.daily_practice_completions completions
on conflict (event_key) do nothing;

insert into public.product_events (
  user_id, experiment_id, event_name, source, event_key, created_at
)
select
  reviews.user_id,
  reviews.experiment_id,
  'weekly_review_opened',
  'weekly_review',
  'review:opened:' || reviews.experiment_id::text,
  reviews.opened_at
from public.weekly_experiment_reviews reviews
on conflict (event_key) do nothing;

insert into public.product_events (
  user_id, experiment_id, event_name, source, event_key, created_at
)
select
  reviews.user_id,
  reviews.experiment_id,
  'weekly_review_completed',
  'weekly_review',
  'review:completed:' || reviews.experiment_id::text,
  reviews.completed_at
from public.weekly_experiment_reviews reviews
where reviews.completed_at is not null
on conflict (event_key) do nothing;

create view analytics.funnel_weekly
with (security_invoker = true)
as
select
  date_trunc('week', created_at)::date as week_start,
  event_name,
  count(*)::bigint as events,
  count(distinct visitor_id)::bigint as unique_visitors,
  count(distinct user_id)::bigint as unique_members
from public.product_events
group by 1, 2;

create view analytics.weekly_activated_members
with (security_invoker = true)
as
select
  date_trunc('week', created_at)::date as week_start,
  count(distinct user_id)::bigint as weekly_activated_members
from public.product_events
where user_id is not null
  and event_name in ('practice_completed', 'weekly_review_completed')
group by 1;

create view analytics.retention_cohorts
with (security_invoker = true)
as
with first_activation as (
  select user_id, min(date_trunc('week', created_at)::date) as cohort_week
  from public.product_events
  where user_id is not null and event_name = 'activation_completed'
  group by user_id
),
cohort_sizes as (
  select cohort_week, count(*)::bigint as cohort_size
  from first_activation
  group by cohort_week
),
target_weeks as (
  select unnest(array[2, 4, 8, 12])::integer as week_number
),
member_activity as (
  select distinct
    user_id,
    date_trunc('week', created_at)::date as activity_week
  from public.product_events
  where user_id is not null
    and event_name in ('practice_completed', 'weekly_review_completed')
)
select
  sizes.cohort_week,
  targets.week_number,
  sizes.cohort_size,
  count(distinct activity.user_id)::bigint as active_members,
  round(count(distinct activity.user_id)::numeric / nullif(sizes.cohort_size, 0), 4) as retention_rate
from cohort_sizes sizes
cross join target_weeks targets
left join first_activation members on members.cohort_week = sizes.cohort_week
left join member_activity activity
  on activity.user_id = members.user_id
 and activity.activity_week = sizes.cohort_week + ((targets.week_number - 1) * 7)
group by sizes.cohort_week, targets.week_number, sizes.cohort_size;

revoke all on analytics.funnel_weekly from public, anon, authenticated;
revoke all on analytics.weekly_activated_members from public, anon, authenticated;
revoke all on analytics.retention_cohorts from public, anon, authenticated;
grant select on analytics.funnel_weekly to service_role;
grant select on analytics.weekly_activated_members to service_role;
grant select on analytics.retention_cohorts to service_role;

comment on table public.product_events is
  'Privacy-minimized product funnel events. Freeform text and health values are prohibited by design.';

comment on view analytics.weekly_activated_members is
  'WAM: distinct members who complete a focused practice or weekly review in a calendar week.';

comment on view analytics.retention_cohorts is
  'Activation cohorts with active-member retention in weeks 2, 4, 8, and 12.';
